<?php
// $Id$

/**
 * @file
 * Define extra meta tags for Drupal pages.
 */

/**
 * Implements hook_form_FORM_ID_alter().
 */
function nodewords_extra_form_nodewords_settings_form_alter(&$form, &$form_state) {
  $form['metatags_creation']['nodewords_add_dc_schema'] = array(
    '#type' => 'checkbox',
    '#title' => t('Add the Dublin Core schema meta tag'),
    '#default_value' => variable_get('nodewords_add_dc_schema', FALSE),
  );
}

/**
 * Implements hook_nodewords_api().
 */
function nodewords_extra_nodewords_api() {
  return array('version' => '1.13');
}

/**
 * Implements hook_nodewords_tags_info().
 */
function nodewords_extra_nodewords_tags_info() {
  $tags = array(
    'dc.contributor' => array(
      'callback' => 'nodewords_extra_dc_contributor',
      'context' => array(
        'allowed' => array(
          NODEWORDS_TYPE_DEFAULT,
          NODEWORDS_TYPE_NODE,
          NODEWORDS_TYPE_PAGE,
        ),
      ),
      'label' => t('Dublin Core contributor'),
      'permission' => 'edit meta tag Dublin Core CONTRIBUTOR',
      'templates' => array(
        'head' => array(
          'dc.contributor' => NODEWORDS_META,
        ),
      ),
    ),
    'dc.creator' => array(
      'callback' => 'nodewords_extra_dc_creator',
      'context' => array(
        'allowed' => array(
          NODEWORDS_TYPE_DEFAULT,
          NODEWORDS_TYPE_NODE,
          NODEWORDS_TYPE_PAGE,
        ),
      ),
      'label' => t('Dublin Core creator'),
      'templates' => array(
        'head' => array(
          'dc.creator' => NODEWORDS_META,
        ),
      ),
    ),
    'dc.date' => array(
      'callback' => 'nodewords_extra_dc_date',
      'context' => array(
        'allowed' => array(
          NODEWORDS_TYPE_DEFAULT,
          NODEWORDS_TYPE_NODE,
          NODEWORDS_TYPE_PAGE,
        ),
      ),
      'label' => t('Dublin Core date'),
      'permission' => 'edit meta tag Dublin Core DATE',
      'templates' => array(
        'head' => array(
          'dc.date' => NODEWORDS_META,
        ),
      ),
    ),
    'dc.description' => array(
      'callback' => 'nodewords_extra_dc_description',
      'label' => t('Dublin Core description'),
      'permission' => 'edit meta tag Dublin Core DESCRIPTION',
      'templates' => array(
        'head' => array(
          'dc.description' => NODEWORDS_META,
        ),
      ),
    ),
    'dc.publisher' => array(
      'callback' => 'nodewords_extra_dc_publisher',
      'context' => array(
        'allowed' => array(
          NODEWORDS_TYPE_DEFAULT,
          NODEWORDS_TYPE_PAGE,
        ),
      ),
      'label' => t('Dublin Core publisher'),
      'permission' => 'edit meta tag Dublin Core PUBLISHER',
      'templates' => array(
        'head' => array(
          'dc.publisher' => NODEWORDS_META,
        ),
      ),
    ),
    'dc.title' => array(
      'context' => array(
        'denied' => array(
          NODEWORDS_TYPE_ERRORPAGE,
          NODEWORDS_TYPE_OFFLINE,
        ),
      ),
      'callback' => 'nodewords_extra_dc_title',
      'label' => t('Dublin Core title'),
      'permission' => 'edit meta tag Dublin Core TITLE',
      'templates' => array(
        'head' => array(
          'dc.title' => NODEWORDS_META,
        ),
      ),
    ),
    'location' => array(
      'callback' => 'nodewords_extra_location',
      'label' => t('Location'),
      'permission' => 'edit location meta tag',
      'templates' => array(
        'head' => array(
          'geo.position' => NODEWORDS_META,
          'icbm' => NODEWORDS_META,
        ),
      ),
    ),
    'shorturl' => array(
      'context' => array(
        'denied' => array(
          NODEWORDS_TYPE_DEFAULT,
          NODEWORDS_TYPE_ERRORPAGE,
          NODEWORDS_TYPE_OFFLINE,
          NODEWORDS_TYPE_TRACKER,
        ),
      ),
      'callback' => 'nodewords_extra_shorturl',
      'label' => t('Short URL'),
      'permission' => 'edit short URL meta tag',
      'templates' => array(
        'head' => array(
          'shorturl' => NODEWORDS_LINK_REL,
        ),
      ),
      'weight' => array('shorturl' => -9),
    ),
  );

  return $tags;
}

function nodewords_extra_nodewords_tags_output_alter(&$output, $parameters) {
  $bool = (
    variable_get('nodewords_add_dc_schema', FALSE) &&
    isset($parameters['output']) &&
    $parameters['type'] != NODEWORDS_TYPE_NONE &&
    $parameters['output'] == 'head'
  );

  if ($bool) {
    $output = (
      '<link rel="schema.dc" href="http://purl.org/dc/elements/1.1/" />' . "\n" .
      $output
    );
  }
}

/**
 * Implements hook_perm().
 */
function nodewords_extra_perm() {
  return array(
    'edit meta tag Dublin Core CONTRIBUTOR',
    'edit meta tag Dublin Core CREATOR',
    'edit meta tag Dublin Core DATE',
    'edit meta tag Dublin Core DESCRIPTION',
    'edit meta tag Dublin Core PUBLISHER',
    'edit meta tag Dublin Core TITLE',
    'edit location meta tag',
    'edit short URL meta tag',
  );
}

/**
 * Set the form fields used to implement the options for the meta tag.
 */
function nodewords_extra_dc_contributor_form(&$form, $content, $options) {
  $form['dc.contributor'] = array(
    '#tree' => TRUE,
  );

  $form['dc.contributor']['value'] = array(
    '#type' => 'textfield',
    '#title' => t('Dublin Core contributor'),
    '#description' => t('Enter the name of an entity responsible for making contributions to the resource. Examples of a contributor include a person, an organization, or a service.'),
    '#default_value' => empty($content['value']) ? (!empty($options['default']['dc.contributor']['value']) ? $options['default']['dc.contributor']['value'] : '') : $content['value'],
    '#size' => 60,
    '#maxlength' => variable_get('nodewords_max_size', 350),
  );
}

/**
 * Set the meta tag content.
 */
function nodewords_extra_dc_contributor_prepare(&$tags, $content, $options) {
  if (!empty($content['value'])) {
    $tags['dc.contributor'] = $content['value'];
  }
  elseif (!empty($options['default']['dc.contributor']['value'])) {
    $tags['dc.contributor'] = $options['default']['dc.contributor']['value'];
  }
}

/**
 * Set the form fields used to implement the options for the meta tag.
 */
function nodewords_extra_dc_creator_form(&$form, $content, $options) {
  $form['dc.creator'] = array(
    '#tree' => TRUE,
  );

  $form['dc.creator']['value'] = array(
    '#type' => 'textfield',
    '#title' => t('Dublin Core creator'),
    '#description' => t('Enter the name of an entity primarily responsible for making the resource. Examples of a creator include a person, an organization, or a service.'),
    '#default_value' => empty($content['value']) ? (!empty($options['default']['dc.creator']['value']) ? $options['default']['dc.creator']['value'] : '') : $content['value'],
    '#size' => 60,
    '#maxlength' => variable_get('nodewords_max_size', 350),
  );
}

/**
 * Set the meta tag content.
 */
function nodewords_extra_dc_creator_prepare(&$tags, $content, $options) {
  if (!empty($content['value'])) {
    $tags['dc.creator'] = $content['value'];
  }
  elseif (!empty($options['default']['dc.creator']['value'])) {
    $tags['dc.creator'] = $options['default']['dc.creator']['value'];
  }
}

/**
 * Set the form fields used to implement the options for the meta tag.
 */
function nodewords_extra_dc_date_form(&$form, $content, $options) {
  $form['dc.date'] = array(
    '#tree' => TRUE,
  );

  $form['dc.date']['value'] = array(
    '#type' => 'date',
    '#title' => t('Dublin Core date'),
    '#description' => t('A point or period of time associated with an event in the lifecycle of the resource. The date should be relative to UTC.'),
    '#default_value' => empty($content['value']) ? array() : $content['value'],
  );
}

/**
 * Set the meta tag content.
 */
function nodewords_extra_dc_date_prepare(&$tags, $content, $options) {
  $time = 0;
  if (!empty($content['value'])) {
    $time = mktime(0, 0, 0, $content['value']['month'], $content['value']['day'], $content['value']['year']);
  }
  elseif (!empty($options['default']['dc.date']['value']['month'])) {
    $time = mktime(0, 0, 0, $options['default']['dc.date']['value']['month'], $options['default']['dc.date']['value']['day'], $options['default']['dc.date']['value']['year']);
  }

  // If a time field was identified, use it.
  if (!empty($time)) {
    $tags['dc.date'] = date('Y-m-d\TH:i:s\Z', $time);
  }
}

/**
 * Set the form fields used to implement the options for the meta tag.
 */
function nodewords_extra_dc_description_form(&$form, $content, $options) {
  if (!isset($form['description'])) {
    $bool = (
      isset($options['node_type']) &&
      variable_get('nodewords_use_teaser_' . $options['node_type'], FALSE)
    );

    if (!$bool) {
      $form['dc.description'] = array(
        '#tree' => TRUE,
      );

      $form['dc.description']['value'] = array(
        '#type' => 'textarea',
        '#title' => t('Description'),
        '#description' => t('Enter a description. Limit your description to about 20 words, with a maximum of %count characters. It should not contain any HTML tags or other formatting.', array('%count' => variable_get('nodewords_max_size', 350))),
        '#default_value' => empty($content['value']) ? (!empty($options['default']['dc.description']['value']) ? $options['default']['dc.description']['value'] : '') : $content['value'],
        '#cols' => 60,
        '#rows' => 6,
        '#wysiwyg' => FALSE,
      );
    }
  }
}

/**
 * Set the meta tag content.
 */
function nodewords_extra_dc_description_prepare(&$tags, $content, $options) {
  if (empty($tags['description'])) {
    if (empty($content['value'])) {
      if (!empty($options['default']['dc.description']['value'])) {
        $value = $options['default']['dc.description']['value'];
      }
      elseif (!empty($options['default']['description']['value'])) {
        $value = $options['default']['description']['value'];
      }
      else {
        $value = '';
      }
    }
    else {
      $value = $content['value'];
    }

    $tags['dc.description'] = $value;
  }
  else {
    $tags['dc.description'] = $tags['description'];
  }
}

/**
 * Set the form fields used to implement the options for the meta tag.
 */
function nodewords_extra_dc_publisher_form(&$form, $content, $options) {
  $form['dc.publisher'] = array(
    '#tree' => TRUE,
  );

  $form['dc.publisher']['value'] = array(
    '#type' => 'textfield',
    '#title' => t('Dublin Core publisher'),
    '#description' => t('Enter a name of an entity responsible for making the resource available. Examples of a publisher include a person, an organization, or a service.'),
    '#default_value' => empty($options['default']['dc.publisher']['value']) ? '' : $options['default']['dc.publisher']['value'],
    '#size' => 60,
    '#maxlength' => variable_get('nodewords_max_size', 350),
  );
}

/**
 * Set the meta tag content.
 */
function nodewords_extra_dc_publisher_prepare(&$tags, $content, $options) {
  // Optional override.
  if (!empty($content['value'])) {
    $tags['dc.publisher'] = $content['value'];
  }
  // Optional default.
  elseif (!empty($options['default']['dc.publisher']['value'])) {
    $tags['dc.publisher'] =  $options['default']['dc.publisher']['value'];
  }
}

/**
 * Set the form fields used to implement the options for the meta tag.
 */
function nodewords_extra_dc_title_form(&$form, $content, $options) {
  $form['dc.title'] = array(
    '#tree' => TRUE,
  );

  $form['dc.title']['value'] = array(
    '#type' => 'textfield',
    '#title' => t('Dublin Core title'),
    '#description' => t('Enter an alternative title. Do not use the value already used for the HTML tag TITLE, or you will probably get warning reports about duplicated titles from the search engines.'),
    '#default_value' => empty($content['value']) ? '' : $content['value'],
    '#size' => 60,
    '#maxlength' => variable_get('nodewords_max_size', 350),
  );
}

/**
 * Set the meta tag content.
 */
function nodewords_extra_dc_title_prepare(&$tags, $content, $options) {
  $tags['dc.title'] = empty($content['value']) ? '' : $content['value'];
}

/**
 * Set the form fields used to implement the options for the meta tag.
 */
function nodewords_extra_location_form(&$form, $content, $options) {
  $latitude = '';
  $longitude = '';

  // Clean up the data.  This is probably an API bug, but for now we'll work
  // around it.
  // TODO: dig into this further, see if it's an API bug.
  if (!empty($content['latitude'])) {
    $data = unserialize($content['latitude']);
    if (is_array($data) && !empty($data['latitude']) && !empty($data['longitude'])) {
      $latitude = $data['latitude'];
      $longitude = $data['longitude'];
    }
  }

  $form['location'] = array(
    '#tree' => TRUE,
  );

  $form['location']['latitude'] = array(
    '#type' => 'textfield',
    '#title' => t('Location coordinates (latitude, longitude)'),
    '#default_value' => $latitude,
    '#element_validate' => array('nodewords_extra_location_form_validate'),
    '#size' => 14,
    '#maxlength' => 14,
    '#prefix' => '<div class="container-inline">',
    '#latitude' => TRUE,
  );

  $form['location']['longitude'] = array(
    '#type' => 'textfield',
    '#title' => '',
    '#default_value' => $longitude,
    '#size' => 14,
    '#element_validate' => array('nodewords_extra_location_form_validate'),
    '#maxlength' => 14,
    '#suffix' => '</div>',
  );
}

/**
 * Validate the values passed as latitude, and longitude.
 */
function nodewords_extra_location_form_validate($element, &$form_state) {
  if (isset($element['#latitude'])) {
    if (!empty($element['#value']) && (!is_numeric($element['#value']) || $element['#value'] < -90.0 || $element['#value'] > 90.0)) {
      form_error($element, t('Latitude must be a number between -90.0 and 90.0 (extrems included).'));
    }
  }
  else {
    if (!empty($element['#value']) && (!is_numeric($element['#value']) || $element['#value'] < -180.0 || $element['#value'] > 180.0)) {
      form_error($element, t('Longitude must be a number between -180.0 and 180.0 (extrems included).'));
    }
  }
}

/**
 * Set the meta tag content.
 */
function nodewords_extra_location_prepare(&$tags, $content, $options) {
  // Load the defaults if at one or more of the lat/long values is invalid.
  if (!isset($content['latitude']) || !is_numeric($content['latitude']) || !isset($content['longitude']) || !is_numeric($content['longitude'])) {
    if (isset($options['default']['location']['latitude']) && is_numeric($options['default']['location']['latitude']) && isset($options['default']['location']['longitude']) && is_numeric($options['default']['location']['longitude'])) {
      $content['latitude'] = $options['default']['location']['latitude'];
      $content['longitude'] = $options['default']['location']['longitude'];
    }
  }

  // Compile the output tag.
  if (isset($content['latitude']) && is_numeric($content['latitude']) && isset($content['longitude']) && is_numeric($content['longitude'])) {
    $tags['location:geo.position'] = $content['latitude'] . ';' . $content['longitude'];
    $tags['location:icbm'] = $content['latitude'] . ',' . $content['longitude'];
  }

  // Optional Location.module integration.
  // @TODO: Shouldn't this override existing data, rather than only be used if
  // nothing was previously set?
  $bool = (
    empty($tags['location:geo.position']) &&
    $options['type'] == NODEWORDS_TYPE_NODE &&
    module_exists('location') &&
    ($node = node_load($options['id'])) &&
    isset($node->locations[0]['latitude']) && is_numeric($node->locations[0]['latitude']) &&
    isset($node->locations[0]['longitude']) && is_numeric($node->locations[0]['longitude'])
  );
  if ($bool) {
    $tags['location:geo.position'] = $node->locations[0]['latitude'] . ';' . $node->locations[0]['longitude'];
    $tags['location:icbm'] = $node->locations[0]['latitude'] . ',' . $node->locations[0]['longitude'];
  }
}

/**
 * Set the form fields used to implement the options for the meta tag.
 */
function nodewords_extra_shorturl_form(&$form, $content, $options) {
  $form['shorturl'] = array(
    '#tree' => TRUE,
  );

  $form['shorturl']['value'] = array(
    '#type' => 'textfield',
    '#title' => t('Short URL'),
    '#description' => t('Short URLs are used instead of the original URL because they are shorter, and easier to remember. Short URLs are provided by some web services, such as <a href="@bitly">bit.ly</a>, <a href="@shorturl">ShortURL</a>, and <a href="@tinyurl">TinyURL</a>.', array('@bitly' => 'http://bit.ly', '@shorturl' => 'http://shorturl.com', '@tinyurl' => 'http://tinyurl.com')),
    '#default_value' => empty($content['value']) ? '' : $content['value'],
    '#element_validate' => array('nodewords_extra_shorturl_form_validate'),
    '#size' => 60,
    '#maxlength' => variable_get('nodewords_max_size', 350),
  );
}

function nodewords_extra_shorturl_form_validate($element, &$form_state) {
  if (!empty($element['#value'])) {
    if (!valid_url(drupal_urlencode($element['#value']), TRUE)) {
      form_error($element, t('The short URL is not a valid absolute URL.'));
    }
  }
}

/**
 * Set the meta tag content.
 */
function nodewords_extra_shorturl_prepare(&$tags, $content, $options) {
  if (!empty($content['value'])) {
    $tags['shorturl'] = check_url($content['value']);
  }
}
