<?php

/**
 * Create a custom menu. Amazing that this does not exist in Drupal core.
 *
 * @param $menu_name
 * @param $menu_title
 * @param $menu_description
 */
function ws_redesign_create_custom_menu($menu_name, $menu_title, $menu_description) {
  $exists = db_result(db_query("SELECT COUNT(*) FROM {menu_custom} WHERE menu_name = '%s'", $menu_name));

  if ($exists == 0) {
    $result = db_query("INSERT INTO {menu_custom} (menu_name, title, description) VALUES ('%s', '%s', '%s')", $menu_name, $menu_title, $menu_description);
    if (!$result) {
      return array('success' => FALSE, 'query' => t('Failed to create custom menu %name', array('%name' => $menu_name)));
    }
  }
  else {
    $result = db_query("UPDATE {menu_custom} SET title = '%s', description = '%s' WHERE menu_name = '%s'", $menu_name, $menu_title, $menu_description);
    if (!$result) {
      return array('success' => FALSE, 'query' => t('Failed to update custom menu %name', array('%name' => $menu_name)));
    }
  }

  return array('success' => TRUE, 'query' => t('Created/Updated custom menu %name', array('%name' => $menu_name)));
}

