<?php

/*
 * @file
 * Advanced Poll Converter Module 4/2/2012 MW
 */

module_load_include('inc', 'advpoll', 'includes/advpoll_voteapi');

/**
 * Implements hook_menu().
 */
function advpoll_converter_menu() {
  $items = array();
  $items['admin/structure/advpoll-converter'] = array(
    'title' => 'Advanced Poll Converter',
    'description' => 'Convert Drupal polls into Advanced Polls.',
    'access callback' => 'user_access',
    'access arguments' => array('administer polls'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('advpoll_converter_form'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'advpoll_converter.admin.inc',
  );

  return $items;
}