<?php
/**
 * @file
 * Provides Rules integration for Workflow.
 *
 * Why it's own module? Some sites prefer rules, some prefer actions,
 * all prefer a lower code footprint and better performance.
 * Additional credit to gcassie ( http://drupal.org/user/80260 ) for
 * the initial push to split rules out of core workflow.
 *
 * This file is intentionally left blanc.
 * The code is in the workflow_rules.workflow.inc file.
 * Drupal 7 requires a .module file, even if it is empty.
 */

module_load_include('inc', 'workflow_rules', 'workflow_rules.rules-callback');
