<?php
// $Id: translatablecomments.module,v 1.1.4.1 2009/11/20 23:38:06 davetrainer Exp $

/**
 * @file
 *
 * Makes comments translatable via the Google AJAX Language API.
 */

/**
 * Implementation of hook_init().
 */
function translatablecomments_init() {
  drupal_add_css(drupal_get_path('module', 'translatablecomments') .'/translatablecomments.css');
  translatablecomments_install_js();
}

/**
 * Implementation of hook_menu.
 */
function translatablecomments_menu() {
  $items['admin/settings/translatablecomments'] = array(
    'title' => "Translatable Comments",
    'access arguments' => array('administer site configuration'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('translatablecomments_admin'),
  );
  return $items;
}

/**
 * Admin configuration form for translatablecomments.
 */
function translatablecomments_admin(&$form_state) {
  $form['translatablecomments_translate_classes'] = array(
    '#type' => 'textfield',
    '#title' => t('CSS Selector for regions to be translated'),
    '#description' => t('Enter a valid css selector for the items to be translated. For example, ".comment .content" would allow translation of comment bodies.'),
    '#default_value' => variable_get('translatablecomments_translate_classes', '.comment .content'),
  );
  $form['translatablecomments_auto_translate'] = array(
    '#type' => 'checkbox',
    '#title' => t("Automatically detect user language and translate."),
    '#description' => t("If this is checked, the user language will be determined from the \$language variable or from the browser language, and if it is different from the language in which the section is written, will be translated automatically."),
    '#default_value' => variable_get('translatablecomments_auto_translate', FALSE),
  );

  return system_settings_form($form);
}

/**
 * Install all the javascript we need to install.
 */
function translatablecomments_install_js() {
  drupal_set_html_head('<script type="text/javascript" src="http://www.google.com/jsapi"></script>');
  drupal_add_js('google.load("language", "1");', 'inline');
  drupal_add_js(drupal_get_path('module', 'translatablecomments') .'/jquery.translatablecomments.js');
  $settings = array(
    'translate_classes' => variable_get('translatablecomments_translate_classes', '.comment .content'),
    'auto_translate' => variable_get('translatablecomments_auto_translate', FALSE),
    'my_language' => substr($GLOBALS['language']->language, 0, 2),
  );
  drupal_add_js(array('translatablecomments' => $settings), "setting");
}

