<?php

/**
 * @file
 * Service for sending contact requests.
 */

/**
 * Implements hook_services_resources() to describe resources provided here
 */
function ws_services_services_resources() {
  $resources = array(
    'hosts' => array(
      'actions' => array(
        'by_location' => array(
          //'file' => array('type' => 'inc', 'module' => 'ws_services', 'name' => 'contact_resource'),
          'callback' => '_ws_services_hosts_by_location',
          'args' => array(
            array(
              'name' => 'minlat',
              'type' => 'float',
              'description' => t('Minimum latitude'),
              'source' => 'data',
            ),
            array(
              'name' => 'maxlat',
              'type' => 'float',
              'description' => t('Maximum latitude.'),
              'source' => 'data',
            ),
            array(
              'name' => 'minlon',
              'type' => 'float',
              'description' => t('Minimum longitude'),
              'source' => 'data',
            ),
            array(
              'name' => 'maxlon',
              'type' => 'float',
              'description' => t('Maximum longitude.'),
              'source' => 'data',
            ),
            array(
              'name' => 'centerlat',
              'type' => 'float',
              'description' => t('Center longitude'),
              'source' => 'data',
            ),
            array(
              'name' => 'centerlon',
              'type' => 'float',
              'description' => t('Center longitude.'),
              'source' => 'data',
            ),
            array(
              'name' => 'limit',
              'type' => 'int',
              'description' => t('Max number of items to return.'),
              'source' => 'data',
              'optional' => TRUE,
              'default value' => 200,
            ),
          ),
          'return' => 'array',
          'help' => t('Returns array of members within the specified coordinates.'),
          'access arguments' => array('access user profiles'),
        ),
        'by_keyword' => array(
          'callback' => '_ws_services_hosts_by_keyword',
          'args' => array(
            array(
              'name' => 'keyword',
              'type' => 'string',
              'description' => t('Keyword'),
              'source' => 'data',
            ),
            array(
              'name' => 'offset',
              'type' => 'int',
              'description' => t("Starting offset within results"),
              'source' => 'data',
            ),
            array(
              'name' => 'limit',
              'type' => 'int',
              'description' => t('Max number of results to return.'),
              'source' => 'data',
            ),
          ),
          'return' => 'array',
          'help' => t('Returns array of members matching keyword.'),
          'access arguments' => array('access user profiles'),
        ),
      ),
    ),
  );
  return $resources;
}


/**
 * Utility function to provide search by location service
 *
 * @param $data
 *   - Array with minlat, maxlat, minlon, maxlon bounding area
 *
 * @return array
 *   - Array of hosts within the bounding area
 */
function _ws_services_hosts_by_location($data) {
  $hosts = wsmap_get_hosts_by_location($data['minlat'], $data['maxlat'], $data['minlon'], $data['maxlon'], $data['centerlat'], $data['centerlon'], $data['limit']);
  foreach ($hosts['accounts'] as &$account) {
    foreach (_ws_services_profile_pictures($account->picture) as $key => $value) {
      $account->$key = $value;
    }
  }
  return $hosts;
}

/**
 * Search hosts by keyword, which can be town, fullname, email, username
 *
 * @param $data
 *   Array of args including:
 *    - keyword
 *    - offset within search results
 *    - limit (max number to return)
 *
 * @return
 *   Array of user accounts
 */
function _ws_services_hosts_by_keyword($data) {
  $keyword = trim($data['keyword']);
  $offset = !empty($data['offset']) ? $data['offset'] : 0;
  $limit = !empty($data['limit']) ? $data['limit'] : variable_get('ws_services_keyword_results_limit', 50);

  try {
    $query = db_select('users', 'u');
    $query->join('wsuser', 'w', 'u.uid = w.uid');
    $query->join('user_location', 'ul', 'u.uid = ul.oid');
    $query->fields('u', array('uid'));

    $query->condition('u.status', 1)
      ->condition(db_or()
        ->condition('u.name', db_like($keys) . '%', 'LIKE')
        ->condition('w.fullname', '%' . db_like($keys) . '%', 'LIKE')
        ->condition('ul.city', db_like($keys) . '%', 'LIKE')
        ->condition('u.mail', $keys));

    // Don't show unvalidated users
    $query->where('u.uid NOT IN (SELECT uid FROM {users_roles} WHERE rid = :rid)', array(':rid' => 9));
    $query->orderBy('w.notcurrentlyavailable');

    // Get array of users matching- array of uid => distance
    $uids = $query
      ->range($offset, $limit)
      ->execute()
      ->fetchCol();

  } catch (Exception $e) {
    watchdog_exception('ws_services', $e);
  }

  $accounts = user_load_multiple($uids);
  foreach ($accounts as &$account) {
    unset($account->pass, $account->mail, $account->data, $account->init, $account->roles, $account->contact, $account->tinymce_status);
    foreach (_ws_services_profile_pictures($account->picture) as $key => $value) {
      $account->$key = $value;
    }
  }
  return array(
    'status' => array(
      'delivered' => count($accounts),
      'status' => 'complete',
    ),
    'query_data' => array(
      'sql' => $query,
      'keyword' => $keyword,
      'offset' => $offset,
      'limit' => $limit,
    ),
    'accounts' => $accounts,
  );

  return $accounts;
}

/**
 * Provide a full set of profile picture possiblities for API users
 *
 * @param $picture_path (from user object)
 * @return array
 */
function _ws_services_profile_pictures($picture_path) {
  $profile_presets = variable_get('wsuser_profile_image_presets', array('mobile_profile_photo_std', 'profile_picture'));
  $pictures = array();
  if (!empty($picture_path)) {
    foreach ($profile_presets as $preset) {
      $pictures["profile_image_{$preset}"] = image_style_path($preset, $picture_path);
    }
  }
  return $pictures;
}
/**
 * Remove inappropriate info from user object retrieved by services.
 *
 * @param $account
 */
function ws_services_services_account_object_alter(&$account) {
  unset($account->data, $account->roles, $account->contact, $account->tinymce_status);

  foreach (_ws_services_profile_pictures($account->picture) as $key => $value) {
    $account->$key = $value;
  }
}
