<?php
// $Id: mobile_theme.module,v 1.1.2.1 2008/05/29 21:13:02 robloach Exp $

/**
 * Check to see if the user is running on a mobile browser.
 */
function mobile_theme_init() {
  $browser = browscap_get_browser();
  if (isset($browser['ismobiledevice'])) {
    if ($browser['ismobiledevice']) {
      $theme = variable_get('mobile_theme_selection', 'default');
      if ($theme != 'default') {
        global $custom_theme;
        $custom_theme = $theme;
      }
    }
  }
}

/**
 * Alter the system theme settings form to add the mobile theme settings.
 */
function mobile_theme_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'system_theme_settings') {
    if ($form['var']['#value'] == 'theme_settings') {
      $themes = array('default' => t('Default'));
      $options = list_themes();
      foreach ($options as $name => $attr) {
        if ($attr->status) {
          $themes[$name] = $attr->info['name'];
        }
      }
      $form['mobile_theme'] = array(
        '#type' => 'fieldset',
        '#prefix' => '<div class="theme-settings-right">',
        '#suffix' => '</div>',
        '#title' => t('Mobile theme'),
        '#description' => t('Choose which theme will be used when the user is on a mobile device. Please note that <em>Browscap</em> must be <a href="@browscapconfigruation">configured properly</a>.', array('@browscapconfigruation' => url('admin/settings/browscap'))),
        'mobile_theme_selection' => array(
          '#type' => 'select',
          '#title' => 'Mobile theme',
          '#description' => t('The theme to use when serving a mobile device.'),
          '#options' => $themes,
          '#default_value' => variable_get('mobile_theme_selection', 'default'),
        ),
        '#weight' => -4,
      );
      $form['#submit'][] = 'mobile_theme_settings_submit';
    }
  }
}

/**
 * Submit handler on the theme settings to save the mobile theme.
 */
function mobile_theme_settings_submit($form, $form_state) {
  if (isset($form_state['values']['mobile_theme_selection'])) {
    variable_set('mobile_theme_selection', $form_state['values']['mobile_theme_selection']);
  }
}
