<?php
/**
 * @file
 * Drupal module: Variable devel
 */

/**
 * Implements hook_menu().
 */
function variable_devel_menu() {
  $items['admin/config/system/variable/type'] = array(
    'title' => 'Types',
    'description' => 'Variable types',
    'page callback' => 'variable_devel_page_type',
    'file' => 'variable_devel.pages.inc',
    'access arguments' => array('administer site configuration'),
    'type' => MENU_LOCAL_TASK,
  );

  $items['admin/config/system/variable/definition/%'] = array(
    'title' => 'Variable types',
    'description' => 'Variable types.',
    'page callback' => 'variable_devel_page_definition',
    'page arguments' => array(5),
    'file' => 'variable_devel.pages.inc',
    'access arguments' => array('administer site configuration'),
    'type' => MENU_CALLBACK,
  );

  $items['admin/config/system/variable/undefined'] = array(
    'title' => 'Undefined',
    'description' => 'Variables not declared by modules',
    'page callback' => 'variable_devel_page_undefined',
    'file' => 'variable_devel.pages.inc',
    'access arguments' => array('administer site configuration'),
    'type' => MENU_LOCAL_TASK,
  );
  return $items;
}

/**
 * Implements hook_variable_settings_form_alter()
 *
 * Compile and display undefined variables.
 */
function variable_devel_variable_settings_form_alter(&$form, &$form_state, $form_id) {
  // Skip some known forms produced by variable module.
  if (isset($form['#variable_edit_form']) || isset($form['#variable_options'])) {
    return;
  }
  module_load_include('inc', 'variable_devel');
  _variable_devel_settings_form_alter($form, $form_state, $form_id);
}
