<?php

// $Id: disablepwstrength.module,v 1.3 2009/05/06 03:35:57 mcrittenden Exp $

/**
 * @file
 * Disable password strength checker using code from 
 *  http://www.drupalcoder.com/story/409-disabling-password-check-in-drupal-6
 *
 */

/**
 * Implementation of hook_init().
 */
function disablepwstrength_init() { 
  if (arg(0) === 'user') {
    drupal_add_js('Drupal.behaviors.password = function () {};', 'inline', 'footer');
  }
}; //hook_init
