<?php

// $Id: warmshowers_site.module 521 2009-06-07 03:41:32Z rfay $

/**
 * @file
 * Site helpers for warmshowers.org
 *
 */



// Alter the user-to-user contact form to (by default) copy the sender
function warmshowers_site_form_contact_mail_user_alter(&$form, $form_state) {
  $form['copy']['#default_value'] = TRUE;
}

/**
 * Alter user profile form.
 * @param $form
 * @param $form_state
 */
function warmshowers_site_form_user_profile_form_alter(&$form, &$form_state) {
  // On submit of user form, go to view instead of staying on edit.
  // $form['#redirect'] = 'user';
}
