<?php

// $Id: warmshowers_site.module 521 2009-06-07 03:41:32Z rfay $

/**
 * @file
 * Site helpers for warmshowers.org
 *
 */



// Alter the user-to-user contact form to (by default) copy the sender
function warmshowers_site_form_contact_mail_user_alter(&$form, $form_state) {
  $form['copy']['#default_value'] = TRUE;
}

// Alter outgoing email to add information about who it is from, etc.
function warmshowers_site_mail_alter(&$message) {
  if ($message['id'] == 'contact_user_mail') {
    $recipient = $message['params']['recipient'];
    $sender = $message['params']['user'];
    $base_url = $GLOBALS['base_url'];
    $langcode = $recipient->language;
    $message['body'][] = "-----------";
    $message['body'][] = t("This email was sent from user !sender (!sender_url) to user !recipient (!recipient_url).",
      array('!sender' => $sender->name, '!sender_email' => $sender->mail, '!recipient' => $recipient->name, '!recipient_email' => $recipient->mail, '!sender_url' => "$base_url/user/{$sender->uid}", '!recipient_url' => "$base_url/user/{$recipient->uid}"), $langcode);
  }
}
/**
 * Alter user profile form.
 * @param $form
 * @param $form_state
 */
function warmshowers_site_form_user_profile_form_alter(&$form, &$form_state) {
  // On submit of user form, go to view instead of staying on edit.
  // $form['#redirect'] = 'user';
}
