<?php
function warmshowers_site_enable() {
  update_sql("UPDATE {system} SET weight = 10 WHERE name = 'warmshowers_site'");
  update_sql("UPDATE {system} SET weight = 30 WHERE name = 'mailsystem'");
}


/**
 * Ah, the problem is that *mailsystem* must run *after* this module so that we can alter
 * the mail before it gets turned into html mail.
 * If htmlmail is not already enabled, this will have to be done
 * manually.
 */
function warmshowers_site_update_6003() {
  $ret = array();
  $ret[] = update_sql("UPDATE {system} SET weight = 10 WHERE name = 'warmshowers_site'");
  $ret[] = update_sql("UPDATE {system} SET weight = 30 WHERE name = 'mailsystem'");
  return $ret;
}
