<?php

/**
 * @file
 * Disable password strength checker.
 *
 * Disable Drupal's built in password strength checker on the user
 * registration and user edit forms. Coder originally taken from
 * http://www.drupalcoder.com/story/409-disabling-password-check-in-drupal-6
 *
 */

/**
 * Implements hook_element_info_alter().
 */
function disablepwstrength_element_info_alter(&$types) {
  if (isset($types['password_confirm']['#process']) && (($position = array_search('user_form_process_password_confirm', $types['password_confirm']['#process'])) !== FALSE)) {
    unset($types['password_confirm']['#process'][$position]);
  }
}

