<?php

/**
 * @file
 *
 * This file contains installation and update hooks for ws_pm_email_notify.
 */

/**
 * Implements hook_uninstall().
 */
function ws_pm_email_notify_uninstall() {
  variable_del('pm_email_notify_body');
  variable_del('pm_email_notify_default');
  variable_del('pm_email_notify_subject');
  variable_del('pm_email_notify_from');
  variable_del('privatemsg_setting_email_notify_level');
  variable_del('privatemsg_setting_email_notify_only_user');
}
