<?php
/**
 * @file
 * Install, update and uninstall functions for the locationservices module.
 *
 */


/* $Id: locationservices.install 505 2009-05-24 18:55:09Z rfay $ */

/**
 * @todo Please document this function.
 * @see http://drupal.org/node/1354
 */
function locationservices_install() {

  $sql = "select @@character_set_database charset";
  $result = db_fetch_object(db_query($sql));
  $current_charset = $result->charset;

  $sql = "set @@character_set_database=utf8";
  db_query($sql);

  $sql = "select @@character_set_database charset";
  $result = db_fetch_object(db_query($sql));
  drupal_set_message("Locationservices_install is being done with character_set_database=$result->charset");


  $tables = "geonames geonames_adm1 geonames_countryinfo user_location_countries user_location_provinces zipcodes";
  foreach (explode(" ", $tables) as $key => $table) {
    drop_if_exists($table);
  }

  $sql =  <<<QUERY
	CREATE TABLE geonames (
  geonameid int(10) unsigned NOT NULL default '0',
  name varchar(200) NOT NULL default '',
  ansiname varchar(200) NOT NULL default '',
  alternames varchar(200) NOT NULL default '',
  latitude double NOT NULL default '0',
  longitude double NOT NULL default '0',
  feature_class char(1) default NULL,
  feature_code varchar(10) default NULL,
  country_code varchar(2) default NULL,
  cc2 varchar(60) default NULL,
  admin1_code varchar(20) default '',
  admin2_code varchar(80) default '',
  admin3_code varchar(20) default '',
  admin4_code varchar(20) default '',
  population int(11) default '0',
  elevation int(11) default '0',
  gtopo30 int(11) default '0',
  timezone varchar(40) default NULL,
  modification_date date default '0000-00-00',
  PRIMARY KEY  (geonameid),
  KEY name (name),
  KEY ansiname (ansiname),
  KEY featurecode (feature_code),
  KEY country_name (country_code,name),
  KEY country_code (country_code),
  KEY admin1code (admin1_code),
  KEY population (population)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

QUERY;

  // TODO Please convert this statement to the D7 database API syntax.
  db_query($sql);

  $sql = <<< QUERY
	
CREATE TABLE geonames_adm1 (
  country_code varchar(2) NOT NULL default '',
  adm1_code varchar(2) NOT NULL default '',
  name varchar(200) NOT NULL default '',
  PRIMARY KEY  (country_code,adm1_code),
  KEY adm1_code (adm1_code),
  KEY country_code (country_code)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
QUERY;
  // TODO Please convert this statement to the D7 database API syntax.
  db_query($sql);

  $sql = <<<QUERY
	
CREATE TABLE geonames_countryinfo (
  iso_alpha2 varchar(2) NOT NULL default '',
  iso_alpha3 varchar(3) NOT NULL default '',
  iso_numeric int(11) NOT NULL default '0',
  fips_code varchar(3) NOT NULL default '',
  name varchar(200) NOT NULL default '',
  capital varchar(100) NOT NULL default '',
  area float NOT NULL default '0',
  population int(11) NOT NULL default '0',
  continent varchar(2) NOT NULL default '',
  languages varchar(100) NOT NULL default '',
  currency varchar(5) NOT NULL default '',
  geonameid int(11) NOT NULL default '0',
  PRIMARY KEY  (iso_alpha2)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
QUERY;

  // TODO Please convert this statement to the D7 database API syntax.
  db_query($sql);

  $sql = <<<QUERY
CREATE TABLE user_location_countries (
  country varchar(2) NOT NULL default '',
  description varchar(60) NOT NULL default '',
  latitude decimal(10,4) NOT NULL default '0.0000',
  longitude decimal(10,4) NOT NULL default '0.0000',
  PRIMARY KEY  (country)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
QUERY;
  // TODO Please convert this statement to the D7 database API syntax.
  db_query($sql);

  $sql = <<<QUERY
	
CREATE TABLE user_location_provinces (
  country varchar(2) NOT NULL default '',
  province varchar(10) NOT NULL default '',
  description varchar(60) NOT NULL default '',
  PRIMARY KEY  (country,province)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
QUERY;
  // TODO Please convert this statement to the D7 database API syntax.
  db_query($sql);

  /**** These won't work on hostgator so have to be loaded with perl script ***
   $geonames_dir=get_absolute_path($geonames_dir = drupal_get_path('module','locationservices') . "/geonames");
   db_query("load data infile '$geonames_dir/outfiles/admin1Codes.processed.txt' into table geonames_adm1");
   db_query("load data infile '$geonames_dir/outfiles/countryInfo_nocomments.txt' into table geonames_countryinfo");
   db_query("load data infile '$geonames_dir/outfiles/allCountries.smaller.txt' into table geonames");

   $mydir = get_absolute_path(drupal_get_path('module','locationservices'));

   db_query("load data infile '$mydir/user_location_countries.txt' into table user_location_countries");
   db_query("load data infile '$mydir/user_location_provinces.txt' into table user_location_provinces");
   ***/


  $sql = "set @@character_set_database=$current_charset";
  // TODO Please convert this statement to the D7 database API syntax.
  db_query($sql);


}

function get_absolute_path($path) {
  if (DIRECTORY_SEPARATOR == '/') {
    $absolute_path = realpath($path);
  }
  else {
    $absolute_path = str_replace('\\', '/', realpath($path)) . '/';
  }
  return $absolute_path;
}

function drop_if_exists($table) {
  $sql = "drop table if exists $table";
  // TODO Please convert this statement to the D7 database API syntax.
  db_query($sql);
}
/**
 * @todo Please document this function.
 * @see http://drupal.org/node/1354
 */
function locationservices_batch_insert($filename) {
  if ($fd = fopen(drupal_get_path('module', 'locationservices') . '/' . $filename, 'r')) {
    while (!feof($fd)) {
      if ($line = fgets($fd)) {
        _db_query(db_prefix_tables($line));
      }
      $line = NULL;
    }
    fclose($fd);
  }
}

/**
 * @todo Please document this function.
 * @see http://drupal.org/node/1354
 */
function locationservices_uninstall() {
  // Remove tables.
  // TODO The drupal_(un)install_schema functions are called automatically in D7.
  // drupal_uninstall_schema('locationservices')

  $tables = "user_location_provinces user_location_countries geonames geonames_adm1 geonames_countryinfo";
  foreach (explode(" ", $tables) as $key => $val) {
    $sql = "drop table if exists $val;";
    // TODO Please convert this statement to the D7 database API syntax.
    db_query($sql);

  }

}


/****** Updates ******************/
