<?php

/**
 * @file
 * Make it possible to machine-translate any element of a page.
 *
 * Adapted from translatableregions module by Dave Trainer.
 */

/**
 * Implementation of hook_init().
 *
 * Add css and javascript for this project if the user has enabled it.
 */
function translatableregions_init() {
  global $user;
  // Install the javascript if either we have configured to always show
  // or the user has NOT turned it off.
  if (user_access('use translatableregions') && (variable_get('translatableregions_always_show_translate_buttons', TRUE) || empty($user->hide_translate_button))) {
    translatableregions_install_js();
  }
}

/**
 * Implements hook_perm()
 */
function translatableregions_perm() {
  return array(
    'use translatableregions',
  );
}
/**
 * Implementation of hook_menu.
 */
function translatableregions_menu() {
  $items['admin/settings/translatableregions'] = array(
    'title' => "Translatable Regions",
    'access arguments' => array('administer site configuration'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('translatableregions_admin'),
  );
  return $items;
}

/**
 * Implementation of hook_block.
 *
 * Provides a single block that allows the user to turn on translation helps.
 */
function translatableregions_block($op = 'list', $delta = '', $edit = array()) {
  // The $op parameter determines what piece of information is being requested.
  switch ($op) {
    case 'list':
      $blocks['configure-auto-translation']['info'] = t('Configure Auto Translation');
      return $blocks;
    case 'view':
      switch ($delta) {
        case 'configure-auto-translation':
          if (user_access('use translatableregions') && $GLOBALS['user']->uid > 0 && !variable_get('translatableregions_always_show_translate_buttons', TRUE)) {
            $block['subject'] = t('Automatic Translation');
            $block['content'] = drupal_get_form('translatableregions_auto_trans_config');
          }
          break;
      }
      return $block;
  }
}

/**
 * The form that provides configuration of translation.
 *
 * This is per-user configuration.
 */
function translatableregions_auto_trans_config(&$form_state) {
  global $user;
  $form['hide_translate_button'] = array(
    '#type' => 'checkbox',
    '#title' => t("Hide automatic translation button"),
    '#default_value' => empty($user->hide_translate_button) ? FALSE : TRUE,
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t("Set"),
  );
  return $form;
}


function translatableregions_auto_trans_config_submit($form, &$form_state) {
  global $user;
  user_save($user, array('hide_translate_button' => $form_state['values']['hide_translate_button']));
}


/**
 * Admin configuration form for translatableregions.
 */
function translatableregions_admin(&$form_state) {
  //TODO: Add what *not* to translate.
  //TODO: add translation of the entire page?
  $form['translatableregions_translation_api_key'] = array(
    '#type' => 'textfield',
    '#title' => t('Translation API key (Google or Microsoft)'),
    '#required' => TRUE,
    '#default_value' => variable_get('translatableregions_translation_api_key', ''),
    '#description' => t('Your key for the Google or Microsoft Translation APIs (obtain the API key @link)', array('%link' => l(t('here'), 'http://www.microsofttranslator.com/dev/'))),
  );
  $form['translatableregions_always_show_translate_buttons'] = array(
    '#type' => 'checkbox',
    '#title' => t("Always show translate buttons"),
    '#description' => t("The translate buttons can be opt-in, based on a setting saved with the user (and configured with the block provided with this module). But if this checkbox is selected, it will be shown regardless, and the block will be disabled."),
    '#default_value' => variable_get('translatableregions_always_show_translate_buttons', TRUE),
  );
  $form['translatableregions_translate_selectors'] = array(
    '#type' => 'textfield',
    '#title' => t('CSS Selector for regions to be translated'),
    '#description' => t('Enter a valid css selector for the items to be translated. For example, ".node, .comment .content" would enable translation of nodes and comment bodies.'),
    '#default_value' => variable_get('translatableregions_translate_selectors', '.node, .comment .content'),
  );
  $form['translatableregions_auto_translate'] = array(
    '#type' => 'checkbox',
    '#title' => t("Automatically detect user language and translate."),
    '#description' => t("If this is checked, the user language will be determined from the \$language variable or from the browser language, and if it is different from the language in which the section is written, will be translated automatically."),
    '#default_value' => variable_get('translatableregions_auto_translate', FALSE),
  );

  return system_settings_form($form);
}

/**
 * Install all the javascript we need to install.
 *
 * jquery translate does most of the work, but also load settings.
 */
function translatableregions_install_js() {
  $core_js = "jquery.translate-NCT,core,NCT-adapter,ui,progress,native.min.js";
  // Uncomment below to use the unminified version.
  // $core_js = "jquery.translate-NCT,core,NCT-adapter,ui,progress,native.js";
  $key = variable_get('translatableregions_translation_api_key', '');
  $path = drupal_get_path('module', 'translatableregions');
  drupal_add_js("$path/jquery.translate/$core_js");
  drupal_add_js("$path/translatableregions.js");

  global $user;
  $settings = array(
    'api_key' => $key,
    'always_show_translate_buttons' => variable_get('translatableregions_always_show_translate_buttons', TRUE),
    'hide_translate_button' => !empty($user->hide_translate_button) ? $user->hide_translate_button : FALSE,
    'translate_selectors' => variable_get('translatableregions_translate_selectors', '.comment .content'),
    'auto_translate' => variable_get('translatableregions_auto_translate', FALSE),
    'browser_language' => translatableregions_language_from_browser(),
  );
  drupal_add_js(array('translatableregions' => $settings), "setting");
}


/**
 * Identify language from the Accept-language HTTP header we got.
 * this is a much simpler adaptation of language_from_browser() in Drupal's
 * language.inc.
 * That one, unfortunately, discards any language that is not configured.
 */
function translatableregions_language_from_browser() {
  // Specified by the user via the browser's Accept Language setting
  // Samples: "hu, en-us;q=0.66, en;q=0.33", "hu,en-us;q=0.5"

  $language = 'en'; // Default language.
  if (isset($_SERVER['HTTP_ACCEPT_LANGUAGE'])) {
    list($language) = explode(",", $_SERVER['HTTP_ACCEPT_LANGUAGE']);
    $language = preg_replace('/-.*$/', '', $language);  // Replace closing '-' which may be present.
  }
  return $language;

}
