<?php
/**
 * @file
 * Provides actions that can be associated to triggers, or used as VBO-action.
 *
 * N.B. This module's name is incorrect. It is not dependent on VBO.
 *
 * Each action is defined in its own file.
 * @see https://drupal.org/node/2052067
 */

/**
 * Implements hook_action_info().
 */
function workflow_vbo_action_info() {
  $actions = array();

  $path = drupal_get_path('module', 'workflow_vbo') . '/actions/';
  include_once $path . 'given.action.inc';
  include_once $path . 'next.action.inc';

  $actions += workflow_vbo_given_action_info();
  $actions += workflow_vbo_next_action_info();

  return $actions;
}
