<?php

/*
 * Implements hook_install().
 */
function slack_install() {
  variable_set('slack_customize_icon', 'none');
}

/*
 * Implements hook_uninstall().
 */
function slack_uninstall() {
  variable_del('slack_webhook_url');
  variable_del('slack_channel');
  variable_del('slack_username');
  variable_del('slack_icon_url');
  variable_del('slack_icon_emoji');
  variable_del('slack_icon_type');
}
