<?php

/*
 * Save a message in the database.
 * $content : content of the message
 * $display_time : time to display the message, default NULL means asap
 * $uid : user to display the message to, default NULL means every user
 * return unique id of message
 */
function db_messages_set_message($content, $uid = NULL, $display_time = NULL) {
  if ($display_time == NULL) {
    $display_time = time();
  }
  $query = "insert into {db_messages} (uid, content, display_time, timestamp) values (%s, '%s', %s ,%s)";
  db_query($query, $uid, $content, $display_time, time());
}

/* function db_messages_get_messages($uid)
 * returns an array of messages owned by user $uid and delete them from the database
 */
function db_messages_get_messages($uid){
  $time = time();
  $result = db_query("select content from db_messages where display_time<$time and uid=$uid order by timestamp asc");
  $messages=array();
  while ($message = db_fetch_object($result)) {
    watchdog('ok',$message->content);
    $messages[] = $message->content;
  }
  db_query("delete from db_messages where display_time<$time and uid=$uid");
  return $messages;
}

/*
 * Implementation of hook_user($op, &$edit, &$account, $category = NULL)
 * display messages on login
 */
function db_messages_user($op, &$edit, &$account, $category = NULL) {
  watchdog('ok','login db messages');
  if ($op == 'login') {
    $messages = db_messages_get_messages($account->uid);
    foreach ($messages as $message){
      drupal_set_message($message);
    }
  }
}
