<?php

function db_messages_schema() {
  $schema['db_messages'] = array(
    'description' => 'The base table to store messages.',
    'fields' => array(
      'mid' => array(
        'description' => 'The primary identifier for a message.',
        'type' => 'serial',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ),
      'uid' => array(
        'descripion' => 'uid of the user who owes the message',
        'type' => 'int',
        'not null' => FALSE,
      ),
      'content' => array(
        'description' => 'The content of the message.',
        'type' => 'text',
        'size' => 'medium',
        'default' => '',
        'not null' => TRUE,
      ),
      'timestamp' => array(
        'description' => 'Time when the message was stored',
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0
      ),
      'display_time' => array(
        'description' => 'Time for the message to be displayed',
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0
      ),
    ),
    
    'unique keys' => array(
      'mid' => array('mid'),
    ),
    'primary key' => array('mid'),
  );
  return $schema;
}

function db_messages_uninstall() {
  drupal_uninstall_schema('db_messages');
  }
  
function db_messages_install() {
  drupal_install_schema('db_messages');
}
