<?php

// $Id: user_location.install 505 2009-05-24 18:55:09Z rfay $


// Consider adding the alter of tablename location to user_location here
// Consider changing wsuser name here to wsuser_full_name
// Load user_location_countries/provinces

// Load geonames* ?
function user_location_install() {
  // Create tables.
  drupal_install_schema('user_location');
}

function rename_location_table() {
	$sql = "rename table location to user_location";
	$result = db_query($sql);
    return array('success' => $result !== FALSE, 'query' => check_plain($sql));

}


