<?php
// $Id: site_verification.module,v 1.1.2.5 2009/09/21 21:05:42 kiam Exp $

/**
 * @file
 * Allows users to add site verification meta tags some web services require.
 */

/**
 * @addtogroup site_verification
 * @{
 */

/**
 * Include the file for the meta tag definitions.
 */
module_load_include('inc', 'site_verification', 'site_verification.metatags');

/*****************************************************************************
 * Drupal hooks.
 ****************************************************************************/

/**
 * Implementation of hook_nodewords_api().
 */
function site_verification_nodewords_api() {
  return array(
    'version' => 1.1,
  );
}

/**
 * Implementation of hook_nodewords_tags_info().
 */
function site_verification_nodewords_tags_info() {
  $tags = array(
    'bing_webmaster_center' => array(
      'tag:context:allowed' => array('frontpage'),
      'tag:db:type' => 'string',
      'tag:function:prefix' => 'site_verification_bing_webmaster_center',
      'tag:template' => array(
        'msvalidate.01' => NODEWORDS_META,
      ),
      'widget:label' => t('Bing Webmaster Center verification code'),
      'widget:permission' => 'edit Bing Webmaster Center verification meta tag',
    ),
    'google_webmaster_tools' => array(
      'tag:context:allowed' => array('frontpage'),
      'tag:db:type' => 'string',
      'tag:function:prefix' => 'site_verification_google_webmaster_tools',
      'tag:template' => array(
        'verify-v1' => NODEWORDS_META,
      ),
      'widget:label' => t('Google Webmaster Tools verification code'),
      'widget:permission' => 'edit Google Webmaster Tools verification meta tag',
    ),
    'yahoo_site_explorer' => array(
      'tag:context:allowed' => array('frontpage'),
      'tag:db:type' => 'string',
      'tag:function:prefix' => 'site_verification_yahoo_site_explorer',
      'tag:template' => array(
        'y_key' => NODEWORDS_META,
      ),
      'widget:label' => t('Yahoo! Site Explorer verification code'),
      'widget:permission' => 'edit Yahoo! Site Explorer verification meta tag',
    ),
  );

  return $tags;
}

/**
 * @} End of "addtogroup site_verification".
 */
