<?php
 /**
  * Implementation of hook_install()
  */
function manage_blocked_install() {
  // Create tables.
  drupal_install_schema('manage_blocked');
}

/**
 * Implementation of hook_uninstall()
 */
function manage_blocked_uninstall(){
  // Remove tables.
  drupal_uninstall_schema('manage_blocked');

  variable_del('manage_blocked_initial');
  variable_del('manage_blocked_frequency');
  variable_del('manage_blocked_total');
  variable_del('manage_blocked_subject');
  variable_del('manage_blocked_msg'); 
}

