{
    "items" : [

        {
            "type"  : "Item",
            "label"   : "none",
            "uid" : "53",
            "nam" : "Tony Starks",
            "tit" : "Mr.",
            "nick" : "ironman",
            "phon" : "555-4321",
            "mbox" : "tony@starksenterprises.com",
            "mbox_sha1sum" : "",
            "openid" : "tony.starks.wutang.com",
            "homepag" : "http",
            "workplaceHomepag" : "http",
            "img" : "",
            "weblog" : "http",
            "member" : "Wu-Tang Clan",
            "jabberID" : "tonys@gmail.com",
            "msnChatID" : "",
            "fn" : "",
            "honorific_prefix" : "Mr.",
            "given_nam" : "Tony",
            "additional_nam" : "Theodore",
            "family_nam" : "Starks",
            "honorific_suffix" : "",
            "adr_typ" : "work",
            "adr_post_office_box" : "P.O Box 421",
            "adr_street_address" : "11 Heart Street",
            "adr_street_address_2" : "Stapleton Projects",
            "adr_extended_address" : "",
            "locality" : "New York",
            "region" : "Staten Island",
            "country_nam" : "USA",
            "tel_mobi" : "666 9876",
            "postal_cod" : "NY",
            "organization_nam" : "Wu-Tang Clan",
            "organization_unit_1" : "2008-06-29 00:47:25",
            "organization_unit_2" : "Unit Test Users",
            "photo" : "",
            "bday" : "a",
            "class" : "public",
            "email_1" : "tony@starksenterprises.com",
            "email_2" : "tonys@gmail.com",
            "tel_work" : "555 4321",
            "category" : ""
        },

        {
            "type"  : "Item",
            "label"   : "none",
            "uid" : "54",
            "nam" : "Elgin Turner",
            "tit" : "Mr.",
            "nick" : "Masta Killa",
            "phon" : "444-4321",
            "mbox" : "masta@wutang.com",
            "mbox_sha1sum" : "",
            "openid" : "masta.killa.openid.org",
            "homepag" : "http",
            "workplaceHomepag" : "http",
            "img" : "http",
            "weblog" : "http",
            "member" : "Wu-Tang Clan",
            "jabberID" : "masta.killa@gmail.com",
            "msnChatID" : "mastakilla@hotmail.com",
            "fn" : "",
            "honorific_prefix" : "Mr.",
            "given_nam" : "Elgin",
            "additional_nam" : "",
            "family_nam" : "Turner",
            "honorific_suffix" : "",
            "adr_typ" : "work",
            "adr_post_office_box" : "P.O Box 768",
            "adr_street_address" : "12 Wu Way",
            "adr_street_address_2" : "Emerson Projects",
            "adr_extended_address" : "",
            "locality" : "Brooklyn",
            "region" : "New York",
            "country_nam" : "2008-06-29 01:47:25",
            "tel_mobi" : "666 0123",
            "postal_cod" : "33267",
            "organization_nam" : "Wu-Tang Clan",
            "organization_unit_1" : "",
            "organization_unit_2" : "Unit Test Users",
            "photo" : "http",
            "bday" : "a",
            "class" : "public",
            "email_1" : "masta.killa@wutang-corp.com",
            "email_2" : "masta.killa@gmail.com",
            "tel_work" : "",
            "category" : ""
        },

        {
            "type"  : "Item",
            "label"   : "none",
            "uid" : "55",
            "nam" : "Lamont Jody Hawkins",
            "tit" : "Mr.",
            "nick" : "U-God",
            "phon" : "555-9987",
            "mbox" : "ugodzilla@wutang.com",
            "mbox_sha1sum" : "",
            "openid" : "ugod.wutang.openid.org",
            "homepag" : "http",
            "workplaceHomepag" : "http",
            "img" : "",
            "weblog" : "http",
            "member" : "Wu-Tang Clan",
            "jabberID" : "ugod@gmail.com",
            "msnChatID" : "",
            "fn" : "Lamont Jody Hawkins",
            "honorific_prefix" : "",
            "given_nam" : "",
            "additional_nam" : "",
            "family_nam" : "",
            "honorific_suffix" : "",
            "adr_typ" : "work",
            "adr_post_office_box" : "",
            "adr_street_address" : "Stapleton Projects",
            "adr_street_address_2" : "",
            "adr_extended_address" : "",
            "locality" : "Brooklyn",
            "region" : "New York",
            "country_nam" : "2008-06-29 01:47:25",
            "tel_mobi" : "+1 868 666 7754",
            "postal_cod" : "4433213",
            "organization_nam" : "Wu-Tang Clan",
            "organization_unit_1" : "Hillside Scramblers",
            "organization_unit_2" : "Unit Test Users",
            "photo" : "",
            "bday" : "a",
            "class" : "",
            "email_1" : "ugodzilla@wutang.com",
            "email_2" : "",
            "tel_work" : "555 1177",
            "category" : ""
        }
    ]
}