<?php
//$Id: views_rdf.module,v 1.1.4.5 2009/09/08 16:37:48 allisterbeharry Exp $
/**
 @file views_rdf.module
 Module definition for views_rdf 
 @see views_rdf.views.inc
*/

function views_rdf_views_api() {
  return array(
    'api' => 2,
  );
}

/**
 * Renders a single user from a view in the
 *
 * @param unknown_type $node
 */
//function views_rdf_sioc_render_xml_user($view_result) {
//	
//}
/**
 * Strips illegal Unicode characters and encodes entities in string
 *
 * @param string $input
 * @return string
 */
function views_rdf_strip_illegal_chars($input) {
//  $output = preg_replace('/[\x{80}-\x{A0}'. // Non-printable ISO-8859-1 + NBSP
//        '\x{01}-\x{1F}'. //Non-printable ASCII characters
//        '\x{AD}'. // Soft-hyphen
//        '\x{2000}-\x{200F}'. // Various space characters
//        '\x{2028}-\x{202F}'. // Bidirectional text overrides
//        '\x{205F}-\x{206F}'. // Various text hinting characters
//        '\x{FEFF}'. // Byte order mark
//        '\x{FF01}-\x{FF60}'. // Full-width latin
//        '\x{FFF9}-\x{FFFD}'. // Replacement characters
//        '\x{0}]/u', // NULL byte
//        '', $input);
//  $output = str_replace('"', '&quot;', $output); //encode quote
//  $output = str_replace('&', '&amp;', $output); //encode ampersand
//  $output = str_replace("'", '&pos;', $output); //encode apostrophe
//  $output = str_replace('<', '&lt;', $output); //encode left-angled bracket
//  $output = str_replace('>', '&rt;', $output); //encode right-angled bracket
  return check_plain(strip_tags($input));
}

/**
 * If input is a serialized date array, return a date string 
 *
 * @param unknown_type $input
 * @return unknown
 */
function views_rdf_is_date ($input) {
  if (strpos($input, 'a:3:{s:5:"month"') !== 0) return $input; 
  else { //serialized date array
    $date = unserialize($input);
    return date(DATE_ISO8601, mktime(0, 0, 0, $date['month'], $date['day'], $date['year']));
  }
}
