<?php
/**
 * @file wsuser.install
 *
 * Updates, installs.
 */
/**
 * Add Index to the fullname column.
 */
function wsuser_update_6001() {
  $ret = array();
  db_add_index($ret, 'wsuser', 'fullname', array('fullname'));
  return $ret;
}

/**
 * Add becomeavailable column to wsuser
 *
 * @return array
 */
function wsuser_update_6002() {
  $ret = array();
  db_add_column($ret, 'wsuser', 'becomeavailable', 'int', array('default' => 0));
  return $ret;
}

/**
 * Add fields related to unavailable marking and pestering.
 *
 * @return array
 */
function wsuser_update_6003() {
  $ret = array();
  // Timestamp at which they set themselves unavailable
  db_add_column($ret, 'wsuser', 'set_unavailable_timestamp', 'int', array('default' => 0));
  // Timestamp at which they set themselves available
  db_add_column($ret, 'wsuser', 'set_available_timestamp', 'int', array('default' => 0));
  // Timestamp when last availability pester was sent
  db_add_column($ret, 'wsuser', 'last_unavailablility_pester', 'int', array('default' => 0));
  return $ret;
}
