<?php

/**
 * Remove old views from system
 */
function ws_d7_upgrade_features_update_7001() {
  // Delete views that we don't want any more
  $unwanted_views = array(
    'admin_content',
    'admin_user_review',
    'admin_users',
    'feedback_counts',
    'flagged_unresponsive',
    'flagged_users',
    'frontpage',
    'login_status',
    'negative_feedbacks_for_user',
    'node_administration',
    'nodes_review',
    'referrals',
    'tips',
    'tutorial_videos',
    'user_flagging',
    'users_with_ordrs',
    'advanced_user_admin',
    'junktest',
  );

  foreach ($unwanted_views as $view_name) {
    $view = views_get_view($view_name);
    if (!empty($view)) {
      $view->delete();
    }
  }
  return t('Removed several old views from the system');
}

/**
 * Add url alias for faq
 */
function ws_d7_upgrade_features_update_7002() {
  $path = array(
    'source' => 'faq-page',
    'alias' => 'faq',
  );
  path_save($path);
  return t("Added path alias for /faq for faq module");
}

