<?php

/**
 * @file
 * Service for sending contact requests.
 */

function ws_services_services_resources() {
  $resources = array(
    'hosts' => array(
      'actions' => array(
        'by_location' => array(
          //'file' => array('type' => 'inc', 'module' => 'ws_services', 'name' => 'contact_resource'),
          'callback' => '_ws_services_hosts_by_location',
          'args' => array(
            array(
              'name' => 'minlat',
              'type' => 'float',
              'description' => t('Minimum latitude'),
              'source' => 'data',
            ),
            array(
              'name' => 'maxlat',
              'type' => 'float',
              'description' => t('Maximum latitude.'),
              'source' => 'data',
            ),
            array(
              'name' => 'minlon',
              'type' => 'float',
              'description' => t('Minimum longitude'),
              'source' => 'data',
            ),
            array(
              'name' => 'maxlon',
              'type' => 'float',
              'description' => t('Maximum longitude.'),
              'source' => 'data',
            ),
            array(
              'name' => 'centerlat',
              'type' => 'float',
              'description' => t('Center longitude'),
              'source' => 'data',
            ),
            array(
              'name' => 'centerlon',
              'type' => 'float',
              'description' => t('Center longitude.'),
              'source' => 'data',
            ),
            array(
              'name' => 'limit',
              'type' => 'int',
              'description' => t('Max number of items to return.'),
              'source' => 'data',
              'optional' => TRUE,
              'default value' => 200,
            ),
          ),
          'return' => 'array',
          'help' => t('Returns array of members within the specified coordinates.'),
          'access arguments' => array('access user profiles'),
        ),
      ),
    ),
    'user_contact' => array(
      'actions' => array(
        'contact' => array(
          //'file' => array('type' => 'inc', 'module' => 'ws_services', 'name' => 'contact_resource'),
          'callback' => '_ws_services_contact_resource',
          'args' => array(
            array(
              'name' => 'uid',
              'type' => 'int',
              'description' => t('The uid of the account to be contacted'),
              'source' => 'data',
            ),
            array(
              'name' => 'subject',
              'type' => 'string',
              'description' => t('The message subject.'),
              'source' => 'data',
            ),
            array(
              'name' => 'message',
              'type' => 'string',
              'description' => t('A message body.'),
              'source' => 'data',
            ),
            array(
              'name' => 'copy',
              'type' => 'bool',
              'description' => t('Set to true if the sending member should receive a copy.'),
              'optional' => TRUE,
              'default value' => TRUE,
              'source' => 'data',
            ),
          ),
          'return' => 'bool',
          'help' => t('Returns TRUE if the message sending was a success.'),
          'access arguments' => array('access user profiles'),
        ),
      ),
    ),
  );
  return $resources;
}

/**
 * Perform a user contact
 *
 * @param $username
 * @param $subject
 * @param $message
 * @param bool $copy
 * @return bool|mixed
 */
function _ws_services_contact_resource($data) {

  // Load the required includes for drupal_execute
  module_load_include('inc', 'contact', 'contact.pages');

  // Set up form_state
  $form_state = array();
  $form_state['values'] = $data;
  $account = user_load($data['uid']);

  if (empty($account)) {
    return services_error(t("Can't send mail to nonexistent user id %d", $data['uid']), 406);
  }

  if (!flood_is_allowed('contact', variable_get('contact_hourly_threshold', 3))) {
    $message = t('You cannot contact more than %number users per hour. Please try again later.', array('%number' => variable_get('contact_hourly_threshold', 3)));
    return services_error($message, 406);
  }

  // When services are deployed, the form will change to warmshowers_site_contact_mail_user
  // We can either change the code or change the variable.
  $form_id = variable_get('ws_services_contact_mail_user_form', 'contact_mail_user');
  $ret = drupal_execute($form_id, $form_state, $account);

  if ($errors = form_get_errors()) {
    return services_error(implode(" ", $errors), 406, array('form_errors' => $errors));
  }
  return array(
    'status' => TRUE,
    'message' => 'The contact was sent',
  );
}



function _ws_services_hosts_by_location($data) {
  $hosts = wsmap_get_hosts_by_location($data['minlat'], $data['maxlat'], $data['minlon'], $data['maxlon'], $data['centerlat'], $data['centerlon'], $data['limit']);
  return $hosts;
}
