<?php

/**
 * @file
 *
 * This file contains installation and update hooks for ws_pm_email_notify.
 */

/**
 * Implements hook_uninstall().
 */
function ws_pm_email_notify_uninstall() {
  variable_del('pm_email_notify_body');
  variable_del('pm_email_notify_default');
  variable_del('pm_email_notify_subject');
  variable_del('ws_pm_email_notify_from');
  variable_del('privatemsg_setting_email_notify_level');
  variable_del('privatemsg_setting_email_notify_only_user');
}


/**
 * Implementation of hook_install().
 */
function ws_pm_email_notify_install() {

}


/**
 * Implements hook_update_N() to create table that determines whether replies
 * go by email or not.
 *
 * @return array
 */
function ws_pm_email_notify_update_6001() {
  $ret = array();

  $schema['ws_pm_email_notify'] = array(
    'description' => "Allow opt-in on reply by email to privatemsg.",
    'fields' => array(
      'uid' => array(
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
        'description' => 'Primary Key: {users}.uid for user.',
      ),
      'email_reply_enabled' => array(
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
        'description' => 'Enable email reply both to and from this user',
      ),
    ),
    'primary_key' => array('uid'),
  );

  db_create_table($ret, 'ws_pm_email_notify', $schema['ws_pm_email_notify']);

  return $ret;
}

/**
 * Implements hook_update_N() to remove the opt-in function on reply-by-email
 *
 * @return array
 */
function ws_pm_email_notify_update_6002() {
  $ret = array();

  db_drop_table($ret, 'ws_pm_email_notify');

  return $ret;
}
